language: ruby

rvm:
  - ruby-head
  - 2.6
  - 2.5
  - rbx-4
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-4
    - rvm: jruby-head

before_install:
  - gem install bundler